export { AboutPage } from './About';
export type { AboutPageProps } from './About';
export { ContactPage } from './Contact';
export type { ContactPageProps } from './Contact';
export { HomePage } from './Home';
export type { HomePageProps } from './Home';
export { JourneyPage } from './Journey';
export type { JourneyPageProps } from './Journey';
export { ProjectsPage } from './Projects';
export { SkillsPage } from './Skills';
export type { SkillsPageProps } from './Skills';
